require "user.plugins"
require "user.settings"
require "user.bindings"
require "user.colorscheme"

require "user.toggle-term"
require "user.colorizer"
require "user.treesitter"
require "user.telescope"
require "user.nvimtree"
require "user.lualine"
require "user.git-signs"
require "user.luasnip"
require "user.which-key"
require "user.zen-mode"
-- require "user.rusttools"

require "user.lsp"
