require "user.packer"
require "user.settings"
require "user.bindings"
require "user.colorscheme"

require "user.toggle-term"
require "user.autopairs"
require "user.lightbulb"
require "user.colorhighlight"
require "user.treesitter"
require "user.telescope"
require "user.nvimtree"
require "user.project"
require "user.lualine"
require "user.luasnip"
require "user.which-key"
require "user.zen-mode"

require "user.lsp-visuals"
require "user.lsp-config"
require "user.lsp-completion"
